### ISSUE TITLE
Question: How can I use this with a trunk/yew site?

### ISSUE THREAD

**Issue by NickLarsenNZ** [storyscript/tracing-wasm#22]
I like the look of this, but I'm unsure how to get it working with a `yew` site run with `trunk`.

`src/main.rs`

```rs
#[function_component(App)]
fn app() -> Html {
    html! {
        <>
        <div class="container">
            <h1>{"Basic Yew Web App"}</h1>
        </div>
        </>
    }
}
fn main() {

    //wasm_logger::init(wasm_logger::Config::default());
    tracing_wasm::set_as_global_default();
    tracing::debug!("App is starting"); // this appears in the console
    tracing::info_span!("we got so far"); // I'm expecting to see something in the Performance inspector.
    yew::start_app::<App>();
}
```

`Cargo.toml`

```toml
[package]
name = "website-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.36"
tracing-wasm = "0.2.1"
yew = "0.19.3"
yew-router = "0.16.0"

```

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yew basic Single Page App</title>
</head>
<body>

</body>
</html>

```

</details>

Run from the repo root with `trunk serve`.
